# Generated by Django 4.1 on 2022-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('realise_date', models.DateTimeField()),
                ('descriptions', models.TextField(max_length=100)),
                ('amount', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'db_table': 'Book',
                'ordering': ['name'],
            },
        ),
    ]
