# Generated by Django 4.1 on 2022-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descriptions',
            field=models.TextField(max_length=350),
        ),
    ]
