# Generated by Django 4.1 on 2022-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
